# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: default

steps:
- task: TerraformTask@5
  displayName: Run Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'TF Service Principal on Azure DevOps'
    backendAzureRmResourceGroupName: 'infra'
    backendAzureRmStorageAccountName: 'satfdata'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'state.tfstate'
- task: TerraformTask@5
  displayName: Run Terraform Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    commandOptions: '-out tfplan'
    environmentServiceNameAzureRM: 'TF Service Principal on Azure DevOps'
- task: TerraformTask@5
  displayName: Run Terraform Apply
  condition: and(succeeded(), eq(variables['terraformPlan.changesPresent'], 'true'))
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: 'tfplan'
    environmentServiceNameAzureRM: 'TF Service Principal on Azure DevOps'