# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - name: planFile
    value: $(Build.SourceVersion).tfplan
  - name: adminVarsFile
    value: $(Build.SourcesDirectory)/pg_admin_pass.auto.tfvars
  - group: admin

steps:
  - task: DownloadSecureFile@1
    name: downloadKeyVaultEnv
    displayName: Download keyvault.env
    inputs:
      secureFile: "keyvault.env"
  - task: AzureCLI@1
    name: downloadAgentPubKey
    displayName: Download agent public key
    inputs:
      azureSubscription: "tf-sp-on-ado"
      scriptType: bash
      scriptLocation: inlineScript
      addSpnToEnvironment: true
      inlineScript: |
        az sshkey show --name $(bookshelf_agent_admin_ssh_pubkey_name) --resource-group $(admin_resource_group_name) --query "publicKey" -o tsv > agent.pub
  - task: AzureCLI@2
    name: downloadAdminPassword
    displayName: Download Postgres Admin Password
    inputs:
      azureSubscription: "tf-sp-on-ado"
      scriptType: bash
      scriptLocation: scriptPath
      scriptPath: $(Build.SourcesDirectory)/get-admin-password.sh
      addSpnToEnvironment: true
      arguments: "$(adminVarsFile) $(downloadKeyVaultEnv.secureFilePath)"
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: latest
  - task: AzureCLI@2
    inputs:
      azureSubscription: "tf-sp-on-ado"
      scriptType: bash
      scriptLocation: inlineScript
      addSpnToEnvironment: true
      inlineScript: |
        ./tf.sh init
    displayName: Terraform Init
    name: terraformInit
  - task: AzureCLI@2
    inputs:
      azureSubscription: "tf-sp-on-ado"
      scriptType: bash
      scriptLocation: inlineScript
      addSpnToEnvironment: true
      inlineScript: |
        ./tf.sh plan -out $(planFile) -var-file=$(adminVarsFile) -var "deployment_principals_object_id=$(deployment_principals_object_id)"
    displayName: Terraform Plan
    name: terraformPlan
  - task: AzureCLI@2
    inputs:
      azureSubscription: "tf-sp-on-ado"
      scriptType: bash
      scriptLocation: inlineScript
      addSpnToEnvironment: true
      inlineScript: |
        ./tf.sh apply $(planFile)
    displayName: Terraform Apply
    name: terraformApply